import streamlit as st
from PIL import Image

from utils.model import load_classifier, predict
from utils.preprocessing import preprocess_image

st.set_page_config(
    page_title="AI vs Real Image Classifier",
    page_icon="🔍",
    layout="centered",
)


@st.cache_resource(show_spinner="Loading model...")
def get_model():
    return load_classifier()


model = get_model()

st.title("AI vs Real Image Classifier")
st.markdown(
    "Upload an image and find out whether it was generated by AI or captured "
    "from the real world. This classifier was trained on a curated dataset of "
    "real and AI-generated images."
)

uploaded = st.file_uploader(
    "Upload an image",
    type=["jpg", "jpeg", "png", "webp"],
    accept_multiple_files=False,
)

if uploaded is None:
    st.info("Upload an image above to get a prediction.")
else:
    image = Image.open(uploaded)

    col1, col2 = st.columns([1, 1])
    with col1:
        st.image(image, caption="Your image", use_container_width=True)

    with col2:
        with st.spinner("Analyzing..."):
            tensor = preprocess_image(image)
            label, confidence = predict(model, tensor)

        if label == "Real":
            st.success(f"### {label}")
        else:
            st.error(f"### {label}")

        st.markdown(f"**Confidence:** {confidence * 100:.1f}%")
        st.progress(confidence)

        with st.expander("What does this mean?"):
            st.write(
                f"The model assigned a {confidence * 100:.1f}% probability "
                f"to its '{label}' prediction. Higher values mean the model "
                "is more certain about its decision."
            )

st.divider()
st.caption(
    "Built with Streamlit · Powered by a custom CNN trained on AI-generated "
    "and real image datasets."
)
